# Generated by Django 4.2.30 on 2026-04-27 18:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "target_url",
                    models.URLField(help_text="Base URL of the target application"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "user_a_credentials",
                    models.JSONField(
                        help_text="Credentials for User A: {login_url, username_field, password_field, username, password, extra_fields}"
                    ),
                ),
                (
                    "user_b_credentials",
                    models.JSONField(
                        help_text="Credentials for User B (same format as User A)"
                    ),
                ),
                (
                    "admin_credentials",
                    models.JSONField(
                        blank=True,
                        help_text="Optional admin credentials for vertical IDOR testing",
                        null=True,
                    ),
                ),
                (
                    "endpoints",
                    models.JSONField(
                        help_text="List of endpoint configs: [{path, method, id_param, id_location, sample_id}]"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional config: {test_methods, check_encoded_ids, check_uuid, check_sequential, custom_headers}",
                    ),
                ),
                ("total_tests", models.IntegerField(default=0)),
                ("vulnerabilities_found", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="scanner.scan",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Informational"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "idor_type",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal Privilege Escalation"),
                            ("vertical", "Vertical Privilege Escalation"),
                            ("data_leak", "Data Leak"),
                            ("unauthorized_modify", "Unauthorized Modification"),
                            ("unauthorized_delete", "Unauthorized Deletion"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "evidence",
                    models.JSONField(
                        help_text="Request/response evidence: {request, response, expected_status, actual_status}"
                    ),
                ),
                ("remediation", models.TextField(blank=True)),
                (
                    "original_id",
                    models.CharField(
                        help_text="The original resource ID", max_length=500
                    ),
                ),
                (
                    "tested_id",
                    models.CharField(
                        help_text="The ID used in the attack", max_length=500
                    ),
                ),
                (
                    "id_location",
                    models.CharField(
                        help_text="Where the ID was found: path, query, body, header",
                        max_length=50,
                    ),
                ),
                ("is_vulnerable", models.BooleanField(default=False)),
                (
                    "ai_analysis",
                    models.TextField(
                        blank=True, help_text="LLM analysis of the finding"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="scanner.scan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
